[package]
name = "symphonia-common"
version = "0.5.4"
description = "Project Symphonia utilities for codecs and formats."
homepage = "https://github.com/pdeljanov/Symphonia"
repository = "https://github.com/pdeljanov/Symphonia"
authors = ["Philip Deljanov <philip.deljanov@gmail.com>"]
license = "MPL-2.0"
readme = "README.md"
categories = ["multimedia", "multimedia::audio", "multimedia::encoding"]
keywords = ["audio", "multimedia", "media", "xiph"]
edition = "2021"
rust-version = "1.77"

[lints]
workspace = true

[dependencies]
symphonia-core = { version = "0.5.4", path = "../symphonia-core" }

[dependencies.symphonia-metadata]
version = "0.5.4"
path = "../symphonia-metadata"
default-features = false
features = ["flac"]
