// Symphonia
// Copyright (c) 2019-2022 The Project Symphonia Developers.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

#[derive(Debug, Copy, Clone, Eq, PartialEq)]
pub(crate) enum Type {
    Master,
    Unsigned,
    Signed,
    Binary,
    String,
    Float,
    Date,
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum ElementType {
    Ebml,
    EbmlVersion,
    EbmlReadVersion,
    EbmlMaxIdLength,
    EbmlMaxSizeLength,
    DocType,
    DocTypeVersion,
    DocTypeReadVersion,
    Crc32,
    Void,
    Segment,
    SeekHead,
    Seek,
    SeekId,
    SeekPosition,
    Info,
    TimestampScale,
    Duration,
    DateUtc,
    Title,
    MuxingApp,
    WritingApp,
    Cluster,
    Timestamp,
    PrevSize,
    SimpleBlock,
    BlockGroup,
    Block,
    BlockAdditions,
    BlockMore,
    BlockAddId,
    BlockAdditional,
    BlockDuration,
    ReferenceBlock,
    DiscardPadding,
    Tracks,
    TrackEntry,
    TrackNumber,
    TrackUid,
    TrackType,
    FlagEnabled,
    FlagDefault,
    FlagForced,
    FlagHearingImpaired,
    FlagVisualImpaired,
    FlagTextDescriptions,
    FlagOriginal,
    FlagCommentary,
    FlagLacing,
    DefaultDuration,
    Name,
    Language,
    CodecId,
    CodecPrivate,
    CodecName,
    CodecDelay,
    SeekPreRoll,
    Video,
    FlagInterlaced,
    StereoMode,
    AlphaMode,
    PixelWidth,
    PixelHeight,
    PixelCropBottom,
    PixelCropTop,
    PixelCropLeft,
    PixelCropRight,
    DisplayWidth,
    DisplayHeight,
    DisplayUnit,
    AspectRatioType,
    Audio,
    SamplingFrequency,
    OutputSamplingFrequency,
    Channels,
    BitDepth,
    ContentEncodings,
    ContentEncoding,
    ContentEncodingOrder,
    ContentEncodingScope,
    ContentEncodingType,
    ContentEncryption,
    ContentEncAlgo,
    ContentEncKeyId,
    ContentEncAesSettings,
    AesSettingsCipherMode,
    Colour,
    MatrixCoefficients,
    BitsPerChannel,
    ChromaSubsamplingHorz,
    ChromaSubsamplingVert,
    CbSubsamplingHorz,
    CbSubsamplingVert,
    ChromaSitingHorz,
    ChromaSitingVert,
    Range,
    TransferCharacteristics,
    Primaries,
    MaxCll,
    MaxFall,
    MasteringMetadata,
    PrimaryRChromaticityX,
    PrimaryRChromaticityY,
    PrimaryGChromaticityX,
    PrimaryGChromaticityY,
    PrimaryBChromaticityX,
    PrimaryBChromaticityY,
    WhitePointChromaticityX,
    WhitePointChromaticityY,
    LuminanceMax,
    LuminanceMin,
    Cues,
    CuePoint,
    CueTime,
    CueTrackPositions,
    CueTrack,
    CueClusterPosition,
    CueRelativePosition,
    CueDuration,
    CueBlockNumber,
    Chapters,
    EditionEntry,
    ChapterAtom,
    ChapterUid,
    ChapterStringUid,
    ChapterTimeStart,
    ChapterTimeEnd,
    ChapterDisplay,
    ChapString,
    ChapLanguage,
    ChapLanguageIetf,
    ChapCountry,
    Tags,
    Tag,
    Targets,
    TargetTypeValue,
    TargetType,
    TagTrackUid,
    SimpleTag,
    TagName,
    TagLanguage,
    TagDefault,
    TagString,
    TagBinary,
    /// Special type for unknown tags.
    Unknown,
}

impl ElementType {
    pub(crate) fn is_top_level(&self) -> bool {
        matches!(
            self,
            ElementType::Cluster
                | ElementType::Cues
                | ElementType::Info
                | ElementType::SeekHead
                | ElementType::Tags
                | ElementType::Tracks
        )
    }
}

pub(crate) static ELEMENTS: phf::Map<u32, (Type, ElementType)> = phf::phf_map! {
    0x1A45DFA3_u32 => (Type::Master, ElementType::Ebml),
    0x4286_u32 => (Type::Unsigned, ElementType::EbmlVersion),
    0x42F7_u32 => (Type::Unsigned, ElementType::EbmlReadVersion),
    0x42F2_u32 => (Type::Unsigned, ElementType::EbmlMaxIdLength),
    0x42F3_u32 => (Type::Unsigned, ElementType::EbmlMaxSizeLength),
    0x4282_u32 => (Type::String, ElementType::DocType),
    0x4287_u32 => (Type::Unsigned, ElementType::DocTypeVersion),
    0x4285_u32 => (Type::Unsigned, ElementType::DocTypeReadVersion),
    0xBF_u32 => (Type::Binary, ElementType::Crc32),
    0xEC_u32 => (Type::Binary, ElementType::Void),
    0x18538067_u32 => (Type::Master, ElementType::Segment),
    0x114D9B74_u32 => (Type::Master, ElementType::SeekHead),
    0x4DBB_u32 => (Type::Master, ElementType::Seek),
    0x53AB_u32 => (Type::Unsigned, ElementType::SeekId),
    0x53AC_u32 => (Type::Unsigned, ElementType::SeekPosition),
    0x1549A966_u32 => (Type::Master, ElementType::Info),
    0x2AD7B1_u32 => (Type::Unsigned, ElementType::TimestampScale),
    0x4489_u32 => (Type::Float, ElementType::Duration),
    0x4461_u32 => (Type::Date, ElementType::DateUtc),
    0x7BA9_u32 => (Type::String, ElementType::Title),
    0x4D80_u32 => (Type::String, ElementType::MuxingApp),
    0x5741_u32 => (Type::String, ElementType::WritingApp),
    0x1F43B675_u32 => (Type::Master, ElementType::Cluster),
    0xE7_u32 => (Type::Unsigned, ElementType::Timestamp),
    0xAB_u32 => (Type::Unsigned, ElementType::PrevSize),
    0xA3_u32 => (Type::Binary, ElementType::SimpleBlock),
    0xA0_u32 => (Type::Master, ElementType::BlockGroup),
    0xA1_u32 => (Type::Binary, ElementType::Block),
    0x75A1_u32 => (Type::Master, ElementType::BlockAdditions),
    0xA6_u32 => (Type::Master, ElementType::BlockMore),
    0xEE_u32 => (Type::Unsigned, ElementType::BlockAddId),
    0xA5_u32 => (Type::Binary, ElementType::BlockAdditional),
    0x9B_u32 => (Type::Unsigned, ElementType::BlockDuration),
    0xFB_u32 => (Type::Signed, ElementType::ReferenceBlock),
    0x75A2_u32 => (Type::Signed, ElementType::DiscardPadding),
    0x1654AE6B_u32 => (Type::Master, ElementType::Tracks),
    0xAE_u32 => (Type::Master, ElementType::TrackEntry),
    0xD7_u32 => (Type::Unsigned, ElementType::TrackNumber),
    0x73C5_u32 => (Type::Unsigned, ElementType::TrackUid),
    0x83_u32 => (Type::Unsigned, ElementType::TrackType),
    0xB9_u32 => (Type::Unsigned, ElementType::FlagEnabled),
    0x88_u32 => (Type::Unsigned, ElementType::FlagDefault),
    0x55AA_u32 => (Type::Unsigned, ElementType::FlagForced),
    0x55AB_u32 => (Type::Unsigned, ElementType::FlagHearingImpaired),
    0x55AC_u32 => (Type::Unsigned, ElementType::FlagVisualImpaired),
    0x55AD_u32 => (Type::Unsigned, ElementType::FlagTextDescriptions),
    0x55AE_u32 => (Type::Unsigned, ElementType::FlagOriginal),
    0x55AF_u32 => (Type::Unsigned, ElementType::FlagCommentary),
    0x9C_u32 => (Type::Unsigned, ElementType::FlagLacing),
    0x23E383_u32 => (Type::Unsigned, ElementType::DefaultDuration),
    0x536E_u32 => (Type::String, ElementType::Name),
    0x22B59C_u32 => (Type::String, ElementType::Language),
    0x86_u32 => (Type::String, ElementType::CodecId),
    0x63A2_u32 => (Type::Binary, ElementType::CodecPrivate),
    0x258688_u32 => (Type::String, ElementType::CodecName),
    0x56AA_u32 => (Type::Unsigned, ElementType::CodecDelay),
    0x56BB_u32 => (Type::Unsigned, ElementType::SeekPreRoll),
    0xE0_u32 => (Type::Master, ElementType::Video),
    0x9A_u32 => (Type::Unsigned, ElementType::FlagInterlaced),
    0x53B8_u32 => (Type::Unsigned, ElementType::StereoMode),
    0x53C0_u32 => (Type::Unsigned, ElementType::AlphaMode),
    0xB0_u32 => (Type::Unsigned, ElementType::PixelWidth),
    0xBA_u32 => (Type::Unsigned, ElementType::PixelHeight),
    0x54AA_u32 => (Type::Unsigned, ElementType::PixelCropBottom),
    0x54BB_u32 => (Type::Unsigned, ElementType::PixelCropTop),
    0x54CC_u32 => (Type::Unsigned, ElementType::PixelCropLeft),
    0x54DD_u32 => (Type::Unsigned, ElementType::PixelCropRight),
    0x54B0_u32 => (Type::Unsigned, ElementType::DisplayWidth),
    0x54BA_u32 => (Type::Unsigned, ElementType::DisplayHeight),
    0x54B2_u32 => (Type::Unsigned, ElementType::DisplayUnit),
    0x54B3_u32 => (Type::Unsigned, ElementType::AspectRatioType),
    0xE1_u32 => (Type::Master, ElementType::Audio),
    0xB5_u32 => (Type::Float, ElementType::SamplingFrequency),
    0x78B5_u32 => (Type::Float, ElementType::OutputSamplingFrequency),
    0x9F_u32 => (Type::Unsigned, ElementType::Channels),
    0x6264_u32 => (Type::Unsigned, ElementType::BitDepth),
    0x6D80_u32 => (Type::Master, ElementType::ContentEncodings),
    0x6240_u32 => (Type::Master, ElementType::ContentEncoding),
    0x5031_u32 => (Type::Unsigned, ElementType::ContentEncodingOrder),
    0x5032_u32 => (Type::Unsigned, ElementType::ContentEncodingScope),
    0x5033_u32 => (Type::Unsigned, ElementType::ContentEncodingType),
    0x5035_u32 => (Type::Master, ElementType::ContentEncryption),
    0x47E1_u32 => (Type::Unsigned, ElementType::ContentEncAlgo),
    0x47E2_u32 => (Type::Unsigned, ElementType::ContentEncKeyId),
    0x47E7_u32 => (Type::Master, ElementType::ContentEncAesSettings),
    0x47E8_u32 => (Type::Unsigned, ElementType::AesSettingsCipherMode),
    0x55B0_u32 => (Type::Master, ElementType::Colour),
    0x55B1_u32 => (Type::Unsigned, ElementType::MatrixCoefficients),
    0x55B2_u32 => (Type::Unsigned, ElementType::BitsPerChannel),
    0x55B3_u32 => (Type::Unsigned, ElementType::ChromaSubsamplingHorz),
    0x55B4_u32 => (Type::Unsigned, ElementType::ChromaSubsamplingVert),
    0x55B5_u32 => (Type::Unsigned, ElementType::CbSubsamplingHorz),
    0x55B6_u32 => (Type::Unsigned, ElementType::CbSubsamplingVert),
    0x55B7_u32 => (Type::Unsigned, ElementType::ChromaSitingHorz),
    0x55B8_u32 => (Type::Unsigned, ElementType::ChromaSitingVert),
    0x55B9_u32 => (Type::Unsigned, ElementType::Range),
    0x55BA_u32 => (Type::Unsigned, ElementType::TransferCharacteristics),
    0x55BB_u32 => (Type::Unsigned, ElementType::Primaries),
    0x55BC_u32 => (Type::Unsigned, ElementType::MaxCll),
    0x55BD_u32 => (Type::Unsigned, ElementType::MaxFall),
    0x55D0_u32 => (Type::Master, ElementType::MasteringMetadata),
    0x55D1_u32 => (Type::Float, ElementType::PrimaryRChromaticityX),
    0x55D2_u32 => (Type::Float, ElementType::PrimaryRChromaticityY),
    0x55D3_u32 => (Type::Float, ElementType::PrimaryGChromaticityX),
    0x55D4_u32 => (Type::Float, ElementType::PrimaryGChromaticityY),
    0x55D5_u32 => (Type::Float, ElementType::PrimaryBChromaticityX),
    0x55D6_u32 => (Type::Float, ElementType::PrimaryBChromaticityY),
    0x55D7_u32 => (Type::Float, ElementType::WhitePointChromaticityX),
    0x55D8_u32 => (Type::Float, ElementType::WhitePointChromaticityY),
    0x55D9_u32 => (Type::Float, ElementType::LuminanceMax),
    0x55DA_u32 => (Type::Float, ElementType::LuminanceMin),
    0x1C53BB6B_u32 => (Type::Master, ElementType::Cues),
    0xBB_u32 => (Type::Master, ElementType::CuePoint),
    0xB3_u32 => (Type::Unsigned, ElementType::CueTime),
    0xB7_u32 => (Type::Master, ElementType::CueTrackPositions),
    0xF7_u32 => (Type::Unsigned, ElementType::CueTrack),
    0xF1_u32 => (Type::Unsigned, ElementType::CueClusterPosition),
    0xF0_u32 => (Type::Unsigned, ElementType::CueRelativePosition),
    0xB2_u32 => (Type::Unsigned, ElementType::CueDuration),
    0x5378_u32 => (Type::Unsigned, ElementType::CueBlockNumber),
    0x1043A770_u32 => (Type::Master, ElementType::Chapters),
    0x45B9_u32 => (Type::Master, ElementType::EditionEntry),
    0xB6_u32 => (Type::Master, ElementType::ChapterAtom),
    0x73C4_u32 => (Type::Unsigned, ElementType::ChapterUid),
    0x5654_u32 => (Type::String, ElementType::ChapterStringUid),
    0x91_u32 => (Type::Unsigned, ElementType::ChapterTimeStart),
    0x92_u32 => (Type::Unsigned, ElementType::ChapterTimeEnd),
    0x80_u32 => (Type::Master, ElementType::ChapterDisplay),
    0x85_u32 => (Type::String, ElementType::ChapString),
    0x437C_u32 => (Type::String, ElementType::ChapLanguage),
    0x437D_u32 => (Type::String, ElementType::ChapLanguageIetf),
    0x437E_u32 => (Type::String, ElementType::ChapCountry),
    0x1254C367_u32 => (Type::Master, ElementType::Tags),
    0x7373_u32 => (Type::Master, ElementType::Tag),
    0x63C0_u32 => (Type::Master, ElementType::Targets),
    0x68CA_u32 => (Type::Unsigned, ElementType::TargetTypeValue),
    0x63CA_u32 => (Type::String, ElementType::TargetType),
    0x63C5_u32 => (Type::Unsigned, ElementType::TagTrackUid),
    0x67C8_u32 => (Type::Master, ElementType::SimpleTag),
    0x45A3_u32 => (Type::String, ElementType::TagName),
    0x447A_u32 => (Type::String, ElementType::TagLanguage),
    0x4484_u32 => (Type::Unsigned, ElementType::TagDefault),
    0x4487_u32 => (Type::String, ElementType::TagString),
    0x4485_u32 => (Type::Binary, ElementType::TagBinary)
};
