#[derive(Debug, Copy, Clone, Eq, PartialEq)]
pub(crate) enum Type {
    Master,
    Unsigned,
    Signed,
    Unknown,
    Binary,
    String,
    Float,
    Date,
}

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum ElementType {
    Ebml,
    EbmlVersion,
    EbmlReadVersion,
    EbmlMaxIdLength,
    EbmlMaxSizeLength,
    DocType,
    DocTypeVersion,
    DocTypeReadVersion,
    Crc32,
    Void,
    Segment,
    SeekHead,
    Seek,
    SeekId,
    SeekPosition,
    Info,
    TimestampScale,
    Duration,
    DateUtc,
    Title,
    MuxingApp,
    WritingApp,
    Cluster,
    Timestamp,
    PrevSize,
    SimpleBlock,
    BlockGroup,
    Block,
    BlockAdditions,
    BlockMore,
    BlockAddId,
    BlockAdditional,
    BlockDuration,
    ReferenceBlock,
    DiscardPadding,
    Tracks,
    TrackEntry,
    TrackNumber,
    TrackUid,
    TrackType,
    FlagEnabled,
    FlagDefault,
    FlagForced,
    FlagHearingImpaired,
    FlagVisualImpaired,
    FlagTextDescriptions,
    FlagOriginal,
    FlagCommentary,
    FlagLacing,
    DefaultDuration,
    Name,
    Language,
    CodecId,
    CodecPrivate,
    CodecName,
    CodecDelay,
    SeekPreRoll,
    Video,
    FlagInterlaced,
    StereoMode,
    AlphaMode,
    PixelWidth,
    PixelHeight,
    PixelCropBottom,
    PixelCropTop,
    PixelCropLeft,
    PixelCropRight,
    DisplayWidth,
    DisplayHeight,
    DisplayUnit,
    AspectRatioType,
    Audio,
    SamplingFrequency,
    OutputSamplingFrequency,
    Channels,
    BitDepth,
    ContentEncodings,
    ContentEncoding,
    ContentEncodingOrder,
    ContentEncodingScope,
    ContentEncodingType,
    ContentEncryption,
    ContentEncAlgo,
    ContentEncKeyId,
    ContentEncAesSettings,
    AesSettingsCipherMode,
    Colour,
    MatrixCoefficients,
    BitsPerChannel,
    ChromaSubsamplingHorz,
    ChromaSubsamplingVert,
    CbSubsamplingHorz,
    CbSubsamplingVert,
    ChromaSitingHorz,
    ChromaSitingVert,
    Range,
    TransferCharacteristics,
    Primaries,
    MaxCll,
    MaxFall,
    MasteringMetadata,
    PrimaryRChromaticityX,
    PrimaryRChromaticityY,
    PrimaryGChromaticityX,
    PrimaryGChromaticityY,
    PrimaryBChromaticityX,
    PrimaryBChromaticityY,
    WhitePointChromaticityX,
    WhitePointChromaticityY,
    LuminanceMax,
    LuminanceMin,
    Cues,
    CuePoint,
    CueTime,
    CueTrackPositions,
    CueTrack,
    CueClusterPosition,
    CueRelativePosition,
    CueDuration,
    CueBlockNumber,
    Chapters,
    EditionEntry,
    ChapterAtom,
    ChapterUid,
    ChapterStringUid,
    ChapterTimeStart,
    ChapterTimeEnd,
    ChapterDisplay,
    ChapString,
    ChapLanguage,
    ChapLanguageIetf,
    ChapCountry,
    Tags,
    Tag,
    Targets,
    TargetTypeValue,
    TargetType,
    TagTrackUid,
    SimpleTag,
    TagName,
    TagLanguage,
    TagDefault,
    TagString,
    TagBinary,
    /// Special type for unknown tags.
    Unknown,
}

pub(crate) const ELEMENTS: [(u32, Type, ElementType); 144] = [
    (0x1A45DFA3, Type::Master, ElementType::Ebml),
    (0x4286, Type::Unsigned, ElementType::EbmlVersion),
    (0x42F7, Type::Unsigned, ElementType::EbmlReadVersion),
    (0x42F2, Type::Unsigned, ElementType::EbmlMaxIdLength),
    (0x42F3, Type::Unsigned, ElementType::EbmlMaxSizeLength),
    (0x4282, Type::String, ElementType::DocType),
    (0x4287, Type::Unsigned, ElementType::DocTypeVersion),
    (0x4285, Type::Unsigned, ElementType::DocTypeReadVersion),
    (0xBF, Type::Binary, ElementType::Crc32),
    (0xEC, Type::Binary, ElementType::Void),
    (0x18538067, Type::Master, ElementType::Segment),
    (0x114D9B74, Type::Master, ElementType::SeekHead),
    (0x4DBB, Type::Master, ElementType::Seek),
    (0x53AB, Type::Unsigned, ElementType::SeekId),
    (0x53AC, Type::Unsigned, ElementType::SeekPosition),
    (0x1549A966, Type::Master, ElementType::Info),
    (0x2AD7B1, Type::Unsigned, ElementType::TimestampScale),
    (0x4489, Type::Float, ElementType::Duration),
    (0x4461, Type::Date, ElementType::DateUtc),
    (0x7BA9, Type::String, ElementType::Title),
    (0x4D80, Type::String, ElementType::MuxingApp),
    (0x5741, Type::String, ElementType::WritingApp),
    (0x1F43B675, Type::Master, ElementType::Cluster),
    (0xE7, Type::Unsigned, ElementType::Timestamp),
    (0xAB, Type::Unsigned, ElementType::PrevSize),
    (0xA3, Type::Binary, ElementType::SimpleBlock),
    (0xA0, Type::Master, ElementType::BlockGroup),
    (0xA1, Type::Binary, ElementType::Block),
    (0x75A1, Type::Master, ElementType::BlockAdditions),
    (0xA6, Type::Master, ElementType::BlockMore),
    (0xEE, Type::Unsigned, ElementType::BlockAddId),
    (0xA5, Type::Binary, ElementType::BlockAdditional),
    (0x9B, Type::Unsigned, ElementType::BlockDuration),
    (0xFB, Type::Signed, ElementType::ReferenceBlock),
    (0x75A2, Type::Signed, ElementType::DiscardPadding),
    (0x1654AE6B, Type::Master, ElementType::Tracks),
    (0xAE, Type::Master, ElementType::TrackEntry),
    (0xD7, Type::Unsigned, ElementType::TrackNumber),
    (0x73C5, Type::Unsigned, ElementType::TrackUid),
    (0x83, Type::Unsigned, ElementType::TrackType),
    (0xB9, Type::Unsigned, ElementType::FlagEnabled),
    (0x88, Type::Unsigned, ElementType::FlagDefault),
    (0x55AA, Type::Unsigned, ElementType::FlagForced),
    (0x55AB, Type::Unsigned, ElementType::FlagHearingImpaired),
    (0x55AC, Type::Unsigned, ElementType::FlagVisualImpaired),
    (0x55AD, Type::Unsigned, ElementType::FlagTextDescriptions),
    (0x55AE, Type::Unsigned, ElementType::FlagOriginal),
    (0x55AF, Type::Unsigned, ElementType::FlagCommentary),
    (0x9C, Type::Unsigned, ElementType::FlagLacing),
    (0x23E383, Type::Unsigned, ElementType::DefaultDuration),
    (0x536E, Type::String, ElementType::Name),
    (0x22B59C, Type::String, ElementType::Language),
    (0x86, Type::String, ElementType::CodecId),
    (0x63A2, Type::Binary, ElementType::CodecPrivate),
    (0x258688, Type::String, ElementType::CodecName),
    (0x56AA, Type::Unsigned, ElementType::CodecDelay),
    (0x56BB, Type::Unsigned, ElementType::SeekPreRoll),
    (0xE0, Type::Master, ElementType::Video),
    (0x9A, Type::Unsigned, ElementType::FlagInterlaced),
    (0x53B8, Type::Unsigned, ElementType::StereoMode),
    (0x53C0, Type::Unsigned, ElementType::AlphaMode),
    (0xB0, Type::Unsigned, ElementType::PixelWidth),
    (0xBA, Type::Unsigned, ElementType::PixelHeight),
    (0x54AA, Type::Unsigned, ElementType::PixelCropBottom),
    (0x54BB, Type::Unsigned, ElementType::PixelCropTop),
    (0x54CC, Type::Unsigned, ElementType::PixelCropLeft),
    (0x54DD, Type::Unsigned, ElementType::PixelCropRight),
    (0x54B0, Type::Unsigned, ElementType::DisplayWidth),
    (0x54BA, Type::Unsigned, ElementType::DisplayHeight),
    (0x54B2, Type::Unsigned, ElementType::DisplayUnit),
    (0x54B3, Type::Unsigned, ElementType::AspectRatioType),
    (0xE1, Type::Master, ElementType::Audio),
    (0xB5, Type::Float, ElementType::SamplingFrequency),
    (0x78B5, Type::Float, ElementType::OutputSamplingFrequency),
    (0x9F, Type::Unsigned, ElementType::Channels),
    (0x6264, Type::Unsigned, ElementType::BitDepth),
    (0x6D80, Type::Master, ElementType::ContentEncodings),
    (0x6240, Type::Master, ElementType::ContentEncoding),
    (0x5031, Type::Unsigned, ElementType::ContentEncodingOrder),
    (0x5032, Type::Unsigned, ElementType::ContentEncodingScope),
    (0x5033, Type::Unsigned, ElementType::ContentEncodingType),
    (0x5035, Type::Master, ElementType::ContentEncryption),
    (0x47E1, Type::Unsigned, ElementType::ContentEncAlgo),
    (0x47E2, Type::Unsigned, ElementType::ContentEncKeyId),
    (0x47E7, Type::Master, ElementType::ContentEncAesSettings),
    (0x47E8, Type::Unsigned, ElementType::AesSettingsCipherMode),
    (0x55B0, Type::Master, ElementType::Colour),
    (0x55B1, Type::Unsigned, ElementType::MatrixCoefficients),
    (0x55B2, Type::Unsigned, ElementType::BitsPerChannel),
    (0x55B3, Type::Unsigned, ElementType::ChromaSubsamplingHorz),
    (0x55B4, Type::Unsigned, ElementType::ChromaSubsamplingVert),
    (0x55B5, Type::Unsigned, ElementType::CbSubsamplingHorz),
    (0x55B6, Type::Unsigned, ElementType::CbSubsamplingVert),
    (0x55B7, Type::Unsigned, ElementType::ChromaSitingHorz),
    (0x55B8, Type::Unsigned, ElementType::ChromaSitingVert),
    (0x55B9, Type::Unsigned, ElementType::Range),
    (0x55BA, Type::Unsigned, ElementType::TransferCharacteristics),
    (0x55BB, Type::Unsigned, ElementType::Primaries),
    (0x55BC, Type::Unsigned, ElementType::MaxCll),
    (0x55BD, Type::Unsigned, ElementType::MaxFall),
    (0x55D0, Type::Master, ElementType::MasteringMetadata),
    (0x55D1, Type::Float, ElementType::PrimaryRChromaticityX),
    (0x55D2, Type::Float, ElementType::PrimaryRChromaticityY),
    (0x55D3, Type::Float, ElementType::PrimaryGChromaticityX),
    (0x55D4, Type::Float, ElementType::PrimaryGChromaticityY),
    (0x55D5, Type::Float, ElementType::PrimaryBChromaticityX),
    (0x55D6, Type::Float, ElementType::PrimaryBChromaticityY),
    (0x55D7, Type::Float, ElementType::WhitePointChromaticityX),
    (0x55D8, Type::Float, ElementType::WhitePointChromaticityY),
    (0x55D9, Type::Float, ElementType::LuminanceMax),
    (0x55DA, Type::Float, ElementType::LuminanceMin),
    (0x1C53BB6B, Type::Master, ElementType::Cues),
    (0xBB, Type::Master, ElementType::CuePoint),
    (0xB3, Type::Unsigned, ElementType::CueTime),
    (0xB7, Type::Master, ElementType::CueTrackPositions),
    (0xF7, Type::Unsigned, ElementType::CueTrack),
    (0xF1, Type::Unsigned, ElementType::CueClusterPosition),
    (0xF0, Type::Unsigned, ElementType::CueRelativePosition),
    (0xB2, Type::Unsigned, ElementType::CueDuration),
    (0x5378, Type::Unsigned, ElementType::CueBlockNumber),
    (0x1043A770, Type::Master, ElementType::Chapters),
    (0x45B9, Type::Master, ElementType::EditionEntry),
    (0xB6, Type::Master, ElementType::ChapterAtom),
    (0x73C4, Type::Unsigned, ElementType::ChapterUid),
    (0x5654, Type::String, ElementType::ChapterStringUid),
    (0x91, Type::Unsigned, ElementType::ChapterTimeStart),
    (0x92, Type::Unsigned, ElementType::ChapterTimeEnd),
    (0x80, Type::Master, ElementType::ChapterDisplay),
    (0x85, Type::String, ElementType::ChapString),
    (0x437C, Type::String, ElementType::ChapLanguage),
    (0x437D, Type::String, ElementType::ChapLanguageIetf),
    (0x437E, Type::String, ElementType::ChapCountry),
    (0x1254C367, Type::Master, ElementType::Tags),
    (0x7373, Type::Master, ElementType::Tag),
    (0x63C0, Type::Master, ElementType::Targets),
    (0x68CA, Type::Unsigned, ElementType::TargetTypeValue),
    (0x63CA, Type::String, ElementType::TargetType),
    (0x63C5, Type::Unsigned, ElementType::TagTrackUid),
    (0x67C8, Type::Master, ElementType::SimpleTag),
    (0x45A3, Type::String, ElementType::TagName),
    (0x447A, Type::String, ElementType::TagLanguage),
    (0x4484, Type::Unsigned, ElementType::TagDefault),
    (0x4487, Type::String, ElementType::TagString),
    (0x4485, Type::Binary, ElementType::TagBinary),
];